### ISSUE TITLE
[feat] 홈화면 : 기능(Back-End) 목록

### ISSUE THREAD

**Issue by crossbell8368** [1OS-DevTeam/TodoPang#18]
## Description ( todo 설명 )

홈화면 동작을 위해 필요한 Back-End 기능제공

## Task ( todo )

* **회원정보 관련**
- [x] 사용자문구 조회

* **프로젝트 관련**
- [x] 홈화면용 정보조회 ( 타이틀 / 물방울 갯수 / 완료되지않은 todo 갯수 / 등록일 / 마감일 )

* **도전과제 관련**
- [x] 홈화면용 정보조회 ( 아이콘 이미지 / 제목 / 설명 )

## Comments

* **프로젝트 관련 예상 데이터타입**
  * 타이틀 : String
  * 물방울 개수 : int
  * todo 개수 : int
  * 등록일 : String ("yyyy-MM-dd HH:mm:ss" 형식)
  * 마감일 : String ("yyyy-MM-dd HH:mm:ss" 형식)

* **프로젝트 관련 추가 데이터**
폭탄 Progress Bar 표현을 위해 추가데이터 제공이 필요한지 궁금합니다!

**Comment by crossbell8368** [comment]
## Description 

* 기획/개발 파트미팅에서 진행내용 반영


## Require Function
파트별 기재된 기능 Func 개발예정

* **회원정보 Part**
  * 사용자 닉네임 select 기능
  * '오늘의 문구' 랜덤추출 기능

* **프로젝트 카드 Part**
  * 활성화 프로젝트ID & 마감일 select 기능
  * 마감일이 빠른 순으로 정렬기능
  * 가장 빠른 프로젝트 3개, 필요정보 select 기능

* **나의 도전과제 Part**
  * 사용자 선택 도전과제 정보select 기능


## Require DataStructure
파트별 기재된 데이터 및 Return 타입 사용예정

* **회원정보 Part**
  * (Need) 사용자 통계 테이블 + '오늘의 문구' 변수
  * (Return) Dictionary 타입 => ["nickname" : val, "phrase" : val]

* **프로젝트 카드 Part**
  * (Need) 프로젝트 테이블 : 타이틀 / 등록된 Todo 개수 / 완료된 Todo 개수 / 시작일 / 마감일
  * (Need) 통계 테이블 : 물방울 개수
  * (Return) Array Dictionaries 타입
  * (Return) [["title" : val, "user_drop" : val, "regist_todo" : val, "complete_todo" : val,, "start_date" : val, "end_date" : val], ...]
  
* **나의 도전과제 Part**
  * (Need) 선택된 도전과제 테이블 : 이미지 / 제목 / 설명
  * (Return) Array Dictionaries 타입 => [["img" : val, "titile" : val, "desc" : val], ...]


## Comment
* 초기, 홈화면에 필요한 모든 데이터를 단일 Function 처리 및 Model에 담아서 Return으로 계획
* 기능 도출 중 파트별 사전 데이터 전처리 과정이 필요할 것으로 예상 됨
* 또한 단일 Function으로 구현 시, 성능 및 예외처리 이슈발생 가능성이 높다고 생각 됨
* 이에 파트별로 Function 구분 & (Array)Dictionary 타입 Return으로 구성

  => **View 및 ViewModel 구성에 있어서 어떤 방식의 data return 이 용이한지 궁금합니다**

**Comment by dotori-0** [comment]
Return 타입은 전부 Struct면 좋을 것 같습니다!

예시) 나의 도전과제 Part
```Swift
struct ChallengeTask {
    let image: UIImage
    let title: String
    let desc: Bool
}

func someMethod() -> [ChallengeTask] {
    return [ChallengeTask(image: UIImage(), title: "과제1", desc: true),
            ChallengeTask(image: UIImage(), title: "과제2", desc: false)]
}
```
