### ISSUE TITLE
[Bug] 도전과제: 화면이슈목록

### ISSUE THREAD

**Issue by crossbell8368** [1OS-DevTeam/TodoPang#57]
## '포기하기' 클릭 시 Fatat Error 발생
* '나의 도전과제'로 등록된 도전과제 클릭 시, Fatal Error 발생
* 발생위치: ChallengeView.swift / 129 line
* **에러화면**
![스크린샷 2023-12-29 오후 6 03 05](https://github.com/1OS-DevTeam/TodoPang/assets/50852143/0d40892f-4b82-4b17-af4c-0593bee462b6)
* **에러로그**
initial count (2). `ForEach(_:content:)` should only be used for *constant* data. Instead conform data to `Identifiable` or use `ForEach(_:id:content:)` and provide an explicit `id`!
ForEach<Range<Int>, Int, ModifiedContent<ModifiedContent<ModifiedContent<ChallengeEmptyView, _BackgroundStyleModifier<Color>>, _ClipEffect<RoundedRectangle>>, AddGestureModifier<_EndedGesture<TapGesture>>>> count (2) != its initial count (1). `ForEach(_:content:)` should only be used for *constant* data. Instead conform data to `Identifiable` or use `ForEach(_:id:content:)` and provide an explicit `id`!
Swift/ContiguousArrayBuffer.swift:600: Fatal error: Index out of range
2023-12-29 18:02:27.563435+0900 teamplan[5024:151341] Swift/ContiguousArrayBuffer.swift:600: Fatal error: Index out of range

* 시뮬레이터 종료 후, 서비스 재구동 후 도전과제 확인 시 '나의 도전과제' 목록에서는 정상적으로 빠져있음을 확인

## '나의 도전과제' 등록 시, 화면 업데이트
* 전체 도전과제에서 나의 도전과제 등록 후, '나의 도전과제'에 바로 적용되지 않는 현상
* 홈화면으로 나갔다가 도전과제 재진입 시, '나의 도전과제' 등록 확인됨
* '나의 도전과제; 등록 후, 전체 도전과제에서는 '도전하기' 버튼이 뜨지 않음을 확인

**Comment by wangkobong** [comment]
'포기하기' 클릭 시 Fatat Error 발생  해결

**Comment by wangkobong** [comment]
도전과제 도전 시작 시 나의 도전과제 화면 업데이트 성공

**Comment by wangkobong** [comment]
모든 이슈 수정 완료

**Comment by crossbell8368** [comment]
## '나의 도전하기' 3개이상 등록가능 이슈

* **이슈 시나리오**
  * '나의 도전과제' 가 3개 모두 등록된 상황
  * 전체 도전과제에서 '나의 도전과제' 등록하기 버튼 클릭 
  * '등록이 완료되었습니다' 팝업 등장
  * '나의 도전과제' 목록에는 노출되지 않음
  
* **정상 시나리오**
  * 더 이상 '나의 도전과제'로 등록이 불가능하다는 경고팝업 등장 필요
  * 경고팝업의 경우, 화면 하단 작은 검은색 바탕의 글씨만 노출되는 형식으로 등장
  * 예시 화면  
<img width="374" alt="스크린샷 2024-01-13 오후 2 57 42" src="https://github.com/1OS-DevTeam/TodoPang/assets/50852143/611a153d-71f6-4998-94cd-0113e263b514">
