### ISSUE TITLE
[Bug] 도전과제 화면: 나의 도전과제 등록이슈

### ISSUE THREAD

**Issue by crossbell8368** [1OS-DevTeam/TodoPang#63]
## '나의 도전하기' 3개이상 등록가능 이슈

* **이슈 시나리오**
  * '나의 도전과제' 가 3개 모두 등록된 상황
  * 전체 도전과제에서 '나의 도전과제' 등록하기 버튼 클릭 
  * '등록이 완료되었습니다' 팝업 등장
  * '나의 도전과제' 목록에는 노출되지 않음
  
* **정상 시나리오**
  * 더 이상 '나의 도전과제'로 등록이 불가능하다는 경고팝업 등장 필요
  * 경고팝업의 경우, 화면 하단 작은 검은색 바탕의 글씨만 노출되는 형식으로 등장
  * 예시 화면  
<img width="374" alt="스크린샷 2024-01-13 오후 2 57 42" src="https://github.com/1OS-DevTeam/TodoPang/assets/50852143/611a153d-71f6-4998-94cd-0113e263b514">

**Comment by wangkobong** [comment]
수정 완료했습니다!
